const {
    REACT_APP_API_URL,
    REACT_APP_NAME,
    REACT_APP_THEME_COLOR,
    REACT_APP_CRYPTO_STORAGE_KEY,
    REACT_APP_CRYPTO_STORAGE_IV,
} = process.env;

const API_URL = REACT_APP_API_URL;
const ADMIN_NAME = REACT_APP_NAME;
const THEME_COLOR = REACT_APP_THEME_COLOR;
const CRYPTO_STORAGE_KEY = REACT_APP_CRYPTO_STORAGE_KEY;
const CRYPTO_STORAGE_IV = REACT_APP_CRYPTO_STORAGE_IV;

export {
    API_URL,
    ADMIN_NAME,
    THEME_COLOR,
    CRYPTO_STORAGE_KEY,
    CRYPTO_STORAGE_IV,
};
